server:
  port: 8082
db:
  config:
    url: jdbc:postgresql://localhost:5432/order
    username: postgres
    password: 123456
spring:
  jpa:
    hibernate:
      ddl-auto: update

rabbitmq:
    url: localhost
    order: ms-order
    product: ms-product